name: Update pull request

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  title-and-description:
    if: github.actor != 'dependabot[bot]' # to avoid running it on Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - name: Add Jira ticket to PR title / add links to PR description
        uses: onrunning/jira-pr-action@v1
        with:
          jira-account: pixelmatters
          ticket-regex: ^FFE-\\d+
          clean-title-regex: ^\\FFE-\\d+\:\ \N*
