name: Update pull request
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  updated_pr:
    if: github.actor != 'dependabot[bot]' # to avoid running it on Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '^([A-Za-z])+-\d+'
          title-template: '%headbranch%: '
          body-template: |
            Jira issue: %headbranch%
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false